# Generated by Django 4.2.20 on 2025-03-28 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organizationuser_candidateuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='mobile',
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='phone',
            field=models.CharField(default='null', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be 10 digits', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='phone',
            field=models.CharField(default='null', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
